//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.19 at 03:47:57 PM EEST 
//


package com.nixsolutions.restlaba.schema.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="header" type="{http://nixsolutions.com/restlaba/schema/beans}Header"/>
 *         &lt;element name="bigBody" type="{http://nixsolutions.com/restlaba/schema/beans}Body"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "bigBody"
})
@XmlRootElement(name = "BigRequest")
public class BigRequest {

    @XmlElement(required = true)
    protected Header header;
    @XmlElement(required = true)
    protected Body bigBody;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the bigBody property.
     * 
     * @return
     *     possible object is
     *     {@link Body }
     *     
     */
    public Body getBigBody() {
        return bigBody;
    }

    /**
     * Sets the value of the bigBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link Body }
     *     
     */
    public void setBigBody(Body value) {
        this.bigBody = value;
    }

}
