//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.19 at 03:47:57 PM EEST 
//


package com.nixsolutions.restlaba.schema.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="smallBody" type="{http://nixsolutions.com/restlaba/schema/beans}SmallBody"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "smallBody"
})
@XmlRootElement(name = "SmallRequest")
public class SmallRequest {

    @XmlElement(required = true)
    protected SmallBody smallBody;

    /**
     * Gets the value of the smallBody property.
     * 
     * @return
     *     possible object is
     *     {@link SmallBody }
     *     
     */
    public SmallBody getSmallBody() {
        return smallBody;
    }

    /**
     * Sets the value of the smallBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmallBody }
     *     
     */
    public void setSmallBody(SmallBody value) {
        this.smallBody = value;
    }

}
